backend:
  name: git-gateway
  branch: main

media_folder: "assets/imagens"
public_folder: "/assets/imagens"

collections:
  - name: "paginas"
    label: "Páginas"
    folder: "HUMANO.MVP"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
